Fix `clippy::inherent_to_string_shadow_display` on `CreationError`
Clippy throws:

    error: type `CreationError` implements inherent method `to_string(&self) -> String` which shadows the implementation of `Display`
       --> glutin/src/lib.rs:317:5
        |
    317 | /     fn to_string(&self) -> String {
    318 | |         match self {
    319 | |             CreationError::OsError(text) | CreationError::NotSupported(text) => text.clone(),
    320 | |             CreationError::NoBackendAvailable(_) => "No backend is available".to_string(),
    ...   |
    333 | |         }
    334 | |     }
        | |_____^
        |
        = note: `#[deny(clippy::inherent_to_string_shadow_display)]` on by default
        = help: remove the inherent method from type `CreationError`
        = help: for further information visit
        https://rust-lang.github.io/rust-clippy/master/index.html#inherent_to_string_shadow_display

To solve this, the contents of the function - which were only consumed
by the `impl Display for CreationError` anyway - have been moved into
that implementation.  The function has been revised to only format a
nested error if the enum variant has one.  Regardless the default
implementation for `source()` returns `None` and doesn't forward to the
deprecated `fn cause()` implementation, which we should probably update
too.